### ISSUE TITLE
import { Subject } from 'rxjs/Subject';

### ISSUE THREAD

**Issue by StaelensC** [Pieter-hogent/web4#1]
Beste

H4. api slide 60..
**import { Subject } from 'rxjs/Subject';** 

geeft bij mij de error: 
_Module '"../../../../../Users/C\u00E9dric Staelens/recipeapp/node_modules/rxjs/Subject"' has no exported member 'Subject'.ts(2305)_

Ik kon het oplossen met : 
**import { Subject } from 'rxjs';**

Mvg

**Comment by Pieter-hogent** [comment]
thanks for reporting the error
